---
# tasks file

- block:
  - name: Make sure cifs package is installed
    apt: pkg="cifs-utils" state=present

  - name: Copy credentials file
    template:
      src: cifscredentials.j2
      dest: "{{ cifs_credentials_file }}"
      owner: root
      group: root
      mode: "u=r,g=r,o=-rwx"

  - name: "mount {{ item.name }} folder"
    mount: 
      state: "mounted" 
      fstype: "cifs"
      name: "{{ item.path }}"
      src: "{{ item.src }}"
      opts: "{{ item.opts }}"
    with_items: "{{ samba_folder }}"

  when: samba_folder is defined